project:
  type: website
  resources:
    - "CNAME"
  render:
    - "*.qmd"                      # only render qmd files

website:
  title: "Metagenomics and amplicon data at MGNify (2025)"
  favicon: static/mgnify_logo.png
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://www.ebi.ac.uk/metagenomics
        text: Open MGnify

  sidebar:
    style: docked
    search: true

    contents: auto

  reader-mode: true


format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true



